Configure TS to generate CommonJS modules
arcana-network/auth pull request #17
Opened 2021-12-20 14:28 UTC by mmjee

2021-12-21 04:47 UTC, mmjee commented
It's probably better to merge #16 before this, this will conflict with that.

2021-12-23 06:21 UTC, makylfang requested changes
The webpack config that was being generated on this auth SDK was not being polyfilled since there are no required polyfills for the auth directly. Since keystore SDK will now export unpolyfilled build now, it needs to be polyfilled at this SDK level so the webpack config should use standalone config instead of module config for generating build meant for CDN's.

@mmjee

2021-12-23 14:54 UTC, mmjee commented
> The webpack config that was being generated on this auth SDK was not being polyfilled since there are no required polyfills for the auth directly. Since keystore SDK will now export unpolyfilled build now, it needs to be polyfilled at this SDK level so the webpack config should use standalone config instead of module config for generating build meant for CDN's.
> 
> @mmjee

Addressed, now using the standalone configuration.

2021-12-23 15:21 UTC, makylfang approved these changes

2021-12-23 15:22 UTC, merged